### ISSUE TITLE
Can't remove security key if name contains special characters like '

### ISSUE THREAD

**Issue by lenz1111** [bartnv/twofactor_webauthn#20]
How to reproduce:
Add security key called "John's key", try to remove it

**Comment by bartnv** [comment]
Ok, that was a bit silly. I quickly hacked in the javascript during prototyping and never bothered to do it properly until now. Fixed in commit [6efe83b](https://github.com/bartnv/twofactor_webauthn/commit/6efe83bee2616048740f38829f030ecbb2cd8cf8).
