### ISSUE TITLE
Change name

### ISSUE THREAD

**Issue by HostOncilla** [bartnv/twofactor_webauthn#23]
Would it be possible to change the following:
`$challenge = $webauthn->prepareChallengeForRegistration(RoundCube, '1', true);`
to:
`$challenge = $webauthn->prepareChallengeForRegistration($rcmail->config->get('product_name'), '1', true);`

That way we can change the name of our webmail.

**Comment by bartnv** [comment]
That's a good idea, thanks for the suggestion. I'll make the change soon.

**Comment by bartnv** [comment]
Fixed in commit [0ab6c28](https://github.com/bartnv/twofactor_webauthn/commit/0ab6c2829d0697e2e7aa282584b66748d547a5ee).
