### ISSUE TITLE
maybe some advise on fido2 keys?

### ISSUE THREAD

**Issue by f1-outsourcing** [bartnv/twofactor_webauthn#25]
Hi, 

Nice integration with windows with this pop-up adding a "Security key setup"! I assume I need to have something like this yubi key to continue from there? Which is a bit unfamiliar territory for me. I was wondering if you know any solutions that turn regular usb drive into auth keys? 
I was browsing a bit and read about this raptor / rohos. But these come with 3rd party services that facilitate some additional daemons/services. I don't want that on my computer. I am looking for something that works with 'default' windows. Maybe some driver that emulates the fido functionality on a regular usb drive?

**Comment by bartnv** [comment]
I'm pretty sure a regular usb drive will not have the required capabilities to act as a security key without supporting software. But there's a variety of hardware manufacturers to choose from if you want a proper FIDO2 key. This is my incomplete list:

https://www.yubico.com/products/security-key/
https://1bitsquared.de/products/solo-key (opensource hardware)
https://shop.trezor.io/product/trezor-model-t (with touchscreen)
https://www.nitrokey.com/products/nitrokeys

**Comment by f1-outsourcing** [comment]
I found this virtual one

https://github.com/bulwarkid/virtual-fido
