### ISSUE TITLE
Title too long in german

### ISSUE THREAD

**Issue by Technikte** [bartnv/twofactor_webauthn#6]
The title  in the settings menu with german translations is a bit too long, so maybe a quick change would fix that.
![grafik](https://user-images.githubusercontent.com/49494924/105531765-1b984a00-5cea-11eb-82a9-bcfbcf86ac36.png)

old
`$labels['config'] = 'Zwei-Faktor Authentifizierung';`

new
`$labels['config'] = '2f Authentifizierung';`

**Comment by bartnv** [comment]
I've changed it to "2-Factor Authentifizierung" and now it fits in my test.
