### ISSUE TITLE
Allow to give a key a name

### ISSUE THREAD

**Issue by jacobkiers** [bartnv/twofactor_webauthn#7]
First off, thank you for this great plugin!

I have a feature request though: could you add the ability to name a key? I have multiple, and by allowing them to be named, I could better distinguish between them.

**Comment by bartnv** [comment]
Yeah, that's a good idea that I intend to implement. It's good practice to have multiple keys registered, in case one of them breaks, so we should make this easy.

**Comment by bartnv** [comment]
Better late than never, I guess! I've just pushed an update which adds this feature.

**Comment by jacobkiers** [comment]
I have moved on from Roundcube in the meantime, but thanks anyway. It's still useful for other users!
